spring:
  profiles:
    active: dev
  #    active: '@profileActive@'

  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: summerice
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: # redis 密码
    database: 1
    timeout: 3000
server:
  port: 8080



mybatis:
  # mapper文件路径
  mapper-locations: classpath:/mapper/*.xml

logging:
  # springboot会自动按天分割日志文件，且非当天的日志会自动压缩为.gz文件
  file:
    name: classpath:/log/my.log

auth:
  jwt:
    header: Authorization
    expire: 604800 # 7天，s为单位
    secret: abcdefghabcdefghabcdefghabcdefgh